print(" Tuple Tasks without loop")



print(" 11. Create tuple of 5 colors")
colors = ('Red', 'Blue', 'Green', 'Yellow', 'Pink')
print(colors)
print()

print("12. Access 1st and last Elements") 
numbers = (10, 20, 30, 40, 50)
print("First Element:", numbers[0])
print("Last Element:", numbers[-1])
print()
print(" 13. tuple Len()")
t = (5, 10, 15, 20)
print("Length:", len(t))
print()
print(" 14. Check Value 25 Present")
t = (10, 20, 25, 30, 35)
print("Is 25 present?", 25 in t)
print()
print(" 15. Concatenate Two Tuples")
t1 = (1, 2, 3)
t2 = (4, 5, 6)
result = t1 + t2
print("Concatenated Tuple:", result)
print()
print(" 16. Find Index and Count")
t = (1, 2, 3, 2, 4, 2, 5)
print("Index of 2:", t.index(2))
print("Count of 2:", t.count(2))
print()
print("17. Convert Tuple to List and Add Element")
t = (1, 2, 3, 4)
lst = list(t)
lst.append(5)
print("List after adding element:", lst)
print()
print("18. Slice Tuple-mid 3 elements")
t = (10, 20, 30, 40, 50, 60)
print("Middle 3 elements:", t[1:4])
print()
print(" 19. Unpack Tuple -3 variables")
fruits = ('Apple', 'Banana', 'Cherry')
a, b, c = fruits
print(a)
print(b)
print(c)
print()
print(" 20. Nested Tuple")
t = (1, 2, (3, 4, 5))
print("Main Tuple:", t)
print("Nested Tuple:", t[2])

