s1=int(input("enter your english mark"))
s2=int(input("enter your tamil mark"))
s3=int(input("enter your maths mark"))
s4=int(input("enter your history mark"))
s5=int(input("enter your geographics mark"))
s6=int(input("enter your politics mark"))
s7=int(input("enter your chemistry mark"))
s8=int(input("enter your physics mark"))
print("english mark :",s1)
print("tamil mark :",s2)
print("maths mark :",s3)
print("history mark :",s4)
print("geographics mark :",s5)
print("politics mark :",s6)
print("chemistry mark :",s7)
print("physics mark :",s8)
total = s1 + s2 + s3 + s4 + s5 +s6 +s7 +s8
print("total :", total)
