print("   bank information    ")
name=input("enter the account holder name:")
num=input("enter the account number:")
code=str(input("enter the ifsc code:"))
branch=input("enter the branch name:")
print("account holder name:",name)
print("account number:",num) 
print("ifsc code:",code)
print("branch name:",branch)
