print("   bank information")
name=input("enter the accountholdername")
num=input("enter the accountnumber")
code=str(input("enter the ifsccode"))
branch=input("enter the branchname")
print("accountholdername:",name)
print("accountnumbern:",num)
print("ifsccode:",code)
print("branchname:",branch)
