name1=(input("enter your name"))
name2=(input("enter your father's name"))           
name3=(input("enter your mother's name"))
name4=(input("enter your sisters's name"))
name5=(input("enter your brother's name"))
print("name :",name1)
print("father's name :",name2)
print("mother's name :",name3)
print("sister's name :",name4)
print("brother's name :",name5)
