print("TUPLE TASK 11")

print( "1. Create a Tuple")
tuple1 = (10, 20, 30, 40, 50)
print("Tuple:", tuple1)
print()
print( " 2. Find the Size of a Tuple")
import sys
print("Size of tuple:", sys.getsizeof(tuple1), "bytes")
print()
print( " 3. Sort Tuples")
tuple2 = (5, 2, 8, 1, 9)
sorted_tuple = tuple(sorted(tuple2))
print("Sorted Tuple:", sorted_tuple)
print()
print( " 4. Tuple with Different Data Types")
tuple3 = (1, "Hello", 3.5, True)
print("Tuple with different data types:", tuple3)
print()
print( " 5. Unpack a Tuple in Several Variables")
tuple4 = ("Apple", "Banana", "Cherry")
(a, b, c) = tuple4
print("Unpacked values:", a, b, c)
print()
print( " 6. Convert a Tuple to a String")
tuple5 = ('P', 'y', 't', 'h', 'o', 'n')
string = ''.join(tuple5)
print("Tuple to String:", string)
print()
print( " 7. Get the 4th element and 4th element from last of a tuple")
tuple6 = (10, 20, 30, 40, 50, 60, 70)
print("4th element:", tuple6[3])

